config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  # Chapter One
  get "chapter_one/d3ia" => 'chapter_one_pages#d3ia'
  get "chapter_one/hello_world" => 'chapter_one_pages#hello_world'
  get "chapter_one/hello_world_circles" => 'chapter_one_pages#hello_world_circles'
  get "chapter_one/d3_conversation" => 'chapter_one_pages#d3_conversation'

  # Chapter Two
  get "chapter_two/selections_and_binding" => 'chapter_two_pages#selections_and_binding'
  get "chapter_two/accessing_data" => 'chapter_two_pages#accessing_data'
  get "chapter_two/integrating_scales" => 'chapter_two_pages#integrating_scales'
  get "chapter_two/bar_chart" => 'chapter_two_pages#bar_chart'
  get "chapter_two/tweets_chart" => 'chapter_two_pages#tweets_chart'
  get "chapter_two/scatterplot" => 'chapter_two_pages#scatterplot'
  get "chapter_two/g_element_labels" => 'chapter_two_pages#g_element_labels'
  get "chapter_two/key_value" => 'chapter_two_pages#key_value'

  # Chapter Three
  get "chapter_three/external_libraries" => 'chapter_three_pages#external_libraries'
  get "chapter_three/events" => 'chapter_three_pages#events'
  get "chapter_three/graphical_transitions" => 'chapter_three_pages#graphical_transitions'
  get "chapter_three/dom_manipulation" => 'chapter_three_pages#dom_manipulation'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chapter_one_pages_controller.rb
class ChapterOnePagesController < ApplicationController
  def d3ia
  end

  def hello_world
  end

  def hello_world_circles
  end

  def d3_conversation
  end
end

app/controllers/chapter_three_pages_controller.rb
class ChapterThreePagesController < ApplicationController

  def external_libraries
  end

  def events
  end

  def graphical_transitions
  end

  def dom_manipulation
  end
end

app/controllers/chapter_two_pages_controller.rb
class ChapterTwoPagesController < ApplicationController

  def selections_and_binding
  end

  def accessing_data
  end

  def integrating_scales
  end

  def bar_chart
  end

  def tweets_chart
  end

  def scatterplot
  end

  def g_element_labels
  end

  def key_value
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapter_one_pages/d3_conversation.html.erb
<h2 id="163">1.6.3 A conversation with D3</h2>

<p><strong>Result:</strong></p>
<div id="vizcontainer">
  <svg style="width:500px;height:500px;border:1px lightgray solid;" />
</div>

<%= javascript_tag do %>
  d3.select("svg")
    .append("circle")
    .attr("r", 20)
    .attr("cx", 20)
    .attr("cy", 20)
    .style("fill", "red");

  d3.select("svg")
    .append("text")
    .attr("id", "a")
    .attr("x", 20)
    .attr("y", 20)
    .style("opacity", 0)
    .text("HELLO WORLD");

  d3.select("svg")
    .append("circle")
    .attr("r", 100)
    .attr("cx", 400)
    .attr("cy", 400)
    .style("fill", "lightblue");

  d3.select("svg")
    .append("text")
    .attr("id", "b")
    .attr("x", 400)
    .attr("y", 400)
    .style("opacity", 0)
    .text("Uh, hi");

  d3.select("#a").transition().delay(1000).style("opacity", 1);
  d3.select("#b").transition().delay(3000).style("opacity", .75);
  d3.selectAll("circle").transition().duration(2000).attr("cy", 200);
<% end %>

app/views/chapter_one_pages/d3ia.html.erb
<div id="infovixDiv">
  <svg style="width:500px;height:500px;border:1px lightgray solid;">
    <path d="M 10, 60 40, 30 50, 50 60, 30 70, 80"
      style="fill:black;stroke:gray;stroke-width:4px;" />
    <polygon style="fill:gray;" points="80, 400 120, 400 160, 440 120, 480 60, 460" />
    <g>
      <circle class="active tentative" cy="100" cx="200" r="30" />
      <rect class="active" x="410" y="200" width="100" height="50"
        style="fill:pink;stroke:black;stroke-width:1px;" />
    </g>
  </svg>
</div>

app/views/chapter_one_pages/hello_world.html.erb
<h2 id="161">1.6.1 Hello World with divs</h2>

<p><strong>Result:</strong></p>
<%= javascript_tag do %>
  d3.select("body").append("div")
    .style("border", "1px black solid")
    .html("hello world");

  d3.select("div")
    .style("background-color", "pink")
    .style("font-size", "24px")
    .attr("class", "d3div")
    .on("click", function() { console.log("You clicked a div") });
<% end %>

app/views/chapter_one_pages/hello_world_circles.html.erb
<h2 id="162">1.6.2 Hello World with circles</h2>

<p><strong>Result:</strong></p>
<div id="vizcontainer">
  <svg style="width:500px;height:500px;border:1px lightgray solid;" />
</div>

<%= javascript_tag do %>
  d3.select("svg")
    .append("line")
    .attr("x1", 20)
    .attr("y1", 20)
    .attr("x2", 400)
    .attr("y2", 400)
    .style("stroke", "black")
    .style("stroke-width", "2px");

  d3.select("svg")
    .append("text")
    .attr("x", 20)
    .attr("y", 20)
    .text("HELLO");

  d3.select("svg")
    .append("circle")
    .attr("r", 20)
    .attr("cx", 20)
    .attr("cy", 20)
    .style("fill", "red");

  d3.select("svg")
    .append("circle")
    .attr("r", 100)
    .attr("cx", 400)
    .attr("cy", 400)
    .style("fill", "lightblue");

  d3.select("svg")
    .append("text")
    .attr("x", 400)
    .attr("y", 400)
    .text("WORLD");
<% end %>

app/views/chapter_three_pages/dom_manipulation.html.erb
<h2>3.2.3 Dom Manipulation</h2><p><strong>Result:</strong></p><div id="viz"><svg style="width:500px;height:500px;border:1px lightgray solid;"></svg></div><div id="controls"></div><%= javascript_tag do %>  // See soccerviz.js.erb  d3.select("body").attr("onload", "createSoccerVizFour()")<% end %>

app/views/chapter_three_pages/events.html.erb
<h2>3.2.1 Events</h2><p><strong>Result:</strong></p><div id="viz"><svg style="width:500px;height:500px;border:1px lightgray solid;" /></div><div id="controls"></div><%= javascript_tag do %>  // See soccerviz.js.erb  d3.select("body").attr("onload", "createSoccerVizTwo()")<% end %>

app/views/chapter_three_pages/external_libraries.html.erb
<h2>3.1.5 External Libraries</h2><p><strong>Result:</strong></p><div id="viz"><svg style="width:500px;height:500px;border:1px lightgray solid;" /></div><div id="controls"></div><%= javascript_tag do %>  // See soccerviz.js.erb  d3.select("body").attr("onload", "createSoccerViz()")<% end %>

app/views/chapter_three_pages/graphical_transitions.html.erb
<h2>3.2.2 Graphical Transitions</h2><p><strong>Result:</strong></p><div id="viz"><svg style="width:500px;height:500px;border:1px lightgray solid;"></svg></div><div id="controls"></div><%= javascript_tag do %>  // See soccerviz.js.erb  d3.select("body").attr("onload", "createSoccerVizThree()")<% end %>

app/views/chapter_two_pages/accessing_data.html.erb
<h2>2.2.2 Accessing data with inline functions</h2>

<p><strong>Result:</strong></p>
<div id="infovizDiv">
  <svg>
  </svg>
</div>
<%= javascript_tag do %>
  d3.select("svg")
    .selectAll("rect")
    .data([15, 50, 22, 8, 100, 10])
    .enter()
    .append("rect")
    .attr("width", 10)
    .attr("height", function(d) { return d; })
    .style("fill", "blue")
    .style("stroke", "red")
    .style("stroke-width", "1px")
    .style("opacity", .25)
    .attr("x", function(d, i) { return i * 10; })
    .attr("y", function(d) { return 100 - d; });
<% end %>

app/views/chapter_two_pages/bar_chart.html.erb
<h2>2.3 Loading data, casting it, measuring it, and displaying it as a bar chart</h2>

<p><strong>Result:</strong></p>
<div id="infovizDiv">
  <svg>
  </svg>
</div>
<%= javascript_tag do %>
  d3.csv("<%= asset_path("cities.csv") %>", function(error, data) { dataViz(data); });
  function dataViz(incomingData) {
    var maxPopulation = d3.max(incomingData, function(el) {
      return parseInt(el.population);
    });

    var yScale = d3.scale.linear().domain([0, maxPopulation]).range([0, 460]);
    d3.select("svg").attr("style", "height: 480px; width: 600px;");
    d3.select("svg")
      .selectAll("rect")
      .data(incomingData)
      .enter()
      .append("rect")
      .attr("width", 50)
      .attr("height", function(d) { return yScale(parseInt(d.population)); })
      .attr("x", function(d, i) { return i * 60; })
      .attr("y", function(d) { return 480 - yScale(parseInt(d.population)); })
      .style("fill", "blue")
      .style("stroke", "red")
      .style("stroke-width", "1px")
      .style("opacity", .25);
  }
<% end %>

app/views/chapter_two_pages/d3ia_continued.html.erb
<h2 id="221">2.2.2 Accessing data with inline functions</h2>

<p><strong>Result:</strong></p>
<div id="infovixDiv">
  <svg>
  </svg>
</div>
<%= javascript_tag do %>
  d3.select("svg")
    .selectAll("rect")
    .data([15, 50, 22, 8, 100, 10])
    .enter()
    .append("rect")
    .attr("width", 10)
    .attr("height", function(d) { return d; })
    .style("fill", "blue")
    .style("stroke", "red")
    .style("stroke-width", "1px")
    .style("opacity", .25)
    .attr("x", function(d, i) { return i * 10; })
    .attr("y", function(d) { return 100 - d; });
<% end %>

app/views/chapter_two_pages/g_element_labels.html.erb
<h2>2.4 Loading, nesting, measuring, and representing data</h2>

<p><strong>Result:</strong></p>
<div id="infovizDiv">
  <svg>
  </svg>
</div>
<%= javascript_tag do %>
  d3.json("<%= asset_path "tweets.json" %>", function(error, data) { dataViz(data.tweets) });
  d3.select("svg").attr("style", "height: 480px; width: 600px;");
  function dataViz(incomingData) {
    incomingData.forEach(function (el) {
      el.impact = el.favorites.length + el.retweets.length;
      el.tweetTime = new Date(el.timestamp);
    })

    var maxImpact = d3.max(incomingData, function(el) { return el.impact; });
    var startEnd = d3.extent(incomingData, function(el) {
      return el.tweetTime;
    });
    var timeRamp = d3.time.scale().domain(startEnd).range([20, 480]);
    var yScale = d3.scale.linear().domain([0, maxImpact]).range([0, 460]);
    var radiusScale = d3.scale.linear()
                        .domain([0, maxImpact]).range([1, 20]);
    var colorScale = d3.scale.linear()
                       .domain([0, maxImpact]).range(["white", "#990000"]);


    d3.select("svg")
      .selectAll("circle")
      .data(incomingData)
      .enter()
      .append("circle")
      .attr("r", function(d) { return radiusScale(d.impact); })
      .attr("cx", function(d, i) { return timeRamp(d.tweetTime); })
      .attr("cy", function(d) { return 480 - yScale(d.impact); })
      .style("fill", function(d) { return colorScale(d.impact); })
      .style("stroke", "black")
      .style("stroke-width", "1px");

    var tweetG = d3.select("svg")
                   .selectAll("g")
                   .data(incomingData)
                   .enter()
                   .append("g")
                   .attr("transform", function(d) {
                     return "translate(" +
                        timeRamp(d.tweetTime) + "," + (480 - yScale(d.impact))
                     + ")";
                   });

    tweetG.append("circle")
          .attr("r", function(d) { return radiusScale(d.impact); })
          .style("fill", "#990000")
          .style("stroke", "black")
          .style("stroke-width", "1px");

    tweetG.append("text")
          .text(function(d) { return d.user + "-" + d.tweetTime.getHours(); });
  }
<% end %>

app/views/chapter_two_pages/integrating_scales.html.erb
<h2>2.2.3 Integrating scales</h2>

<p><strong>Result:</strong></p>
<div id="infovizDiv">
  <svg>
  </svg>
</div>
<%= javascript_tag do %>
  var yScale = d3.scale.linear()
                 .domain([0, 100, 500])
                 .range([0, 50, 100])
                 .clamp(true);
                 
  d3.select("svg")
    .selectAll("rect")
    .data([14, 68, 24500, 430, 19, 1000, 5555])
    .enter()
    .append("rect")
    .attr("width", 10)
    .attr("height", function(d) { return yScale(d); })
    .style("fill", "blue")
    .style("stroke", "red")
    .style("stroke-width", "1px")
    .style("opacity", .25)
    .attr("x", function(d, i) { return i * 10; })
    .attr("y", function(d) { return 100 - yScale(d); });
<% end %>

app/views/chapter_two_pages/key_value.html.erb
<h2>2.7 Setting the key value in data-binding</h2>

<p><strong>Result:</strong></p>
<div id="infovizDiv">
  <svg>
  </svg>
</div>
<%= javascript_tag do %>
  d3.json("<%= asset_path "tweets.json" %>", function(error, data) { dataViz(data.tweets) });
  d3.select("svg").attr("style", "height: 480px; width: 600px;");
  function dataViz(incomingData) {
    incomingData.forEach(function (el) {
      el.impact = el.favorites.length + el.retweets.length;
      el.tweetTime = new Date(el.timestamp);
    })

    var maxImpact = d3.max(incomingData, function(el) { return el.impact; });
    var startEnd = d3.extent(incomingData, function(el) {
      return el.tweetTime;
    });
    var timeRamp = d3.time.scale().domain(startEnd).range([20, 450]);
    var yScale = d3.scale.linear().domain([0, maxImpact]).range([0, 460]);
    var radiusScale = d3.scale.linear()
                        .domain([0, maxImpact]).range([1, 20]);
    var colorScale = d3.scale.linear()
                       .domain([0, maxImpact]).range(["white", "#990000"]);


    d3.select("svg")
      .selectAll("circle")
      .data(incomingData, function(d) {
        return JSON.stringify(d)
      })
      .enter()
      .append("circle")
      .attr("r", function(d) { return radiusScale(d.impact); })
      .attr("cx", function(d, i) { return timeRamp(d.tweetTime); })
      .attr("cy", function(d) { return 480 - yScale(d.impact); })
      .style("fill", function(d) { return colorScale(d.impact); })
      .style("stroke", "black")
      .style("stroke-width", "1px");

    var filteredData = incomingData.filter(
      function(el) { return el.impact > 0 }
    );
    d3.selectAll("circle")
      .data(filteredData, function(d) { return JSON.stringify(d) })
      .exit()
      .remove();
  }
<% end %>

app/views/chapter_two_pages/scatterplot.html.erb
<h2>2.5 Creating a scatterplot</h2>

<p><strong>Result:</strong></p>
<div id="infovizDiv">
  <svg>
  </svg>
</div>
<%= javascript_tag do %>
  d3.json("<%= asset_path "tweets.json" %>", function(error, data) { dataViz(data.tweets) });

  function dataViz(incomingData) {
    incomingData.forEach(function (el) {
      el.impact = el.favorites.length + el.retweets.length;
      el.tweetTime = new Date(el.timestamp);
    })

    var maxImpact = d3.max(incomingData, function(el) { return el.impact; });
    var startEnd = d3.extent(incomingData, function(el) {
      return el.tweetTime;
    });
    var timeRamp = d3.time.scale().domain(startEnd).range([20, 480]);
    var yScale = d3.scale.linear().domain([0, maxImpact]).range([0, 460]);
    var radiusScale = d3.scale.linear()
                        .domain([0, maxImpact]).range([1, 20]);
    var colorScale = d3.scale.linear()
                       .domain([0, maxImpact]).range(["white", "#990000"]);

    d3.select("svg").attr("style", "height: 480px; width: 600px;");
    d3.select("svg")
      .selectAll("circle")
      .data(incomingData)
      .enter()
      .append("circle")
      .attr("r", function(d) { return radiusScale(d.impact); })
      .attr("cx", function(d, i) { return timeRamp(d.tweetTime); })
      .attr("cy", function(d) { return 480 - yScale(d.impact); })
      .style("fill", function(d) { return colorScale(d.impact); })
      .style("stroke", "black")
      .style("stroke-width", "1px");
  }
<% end %>

app/views/chapter_two_pages/selections_and_binding.html.erb
<h2 id="221">2.2.1 Selections and Binding</h2>

<p><strong>Result:</strong></p>
<%= javascript_tag do %>
  d3.csv("<%= asset_path("cities.csv") %>", function(error, data) { dataViz(data); });
  function dataViz(incomingData) {
    console.log(incomingData)
    d3.select("body").selectAll("div.cities")
      .data(incomingData)
      .enter()
      .append("div")
      .attr("class", "cities")
      .html(function(d, i) { return d.label });
  }
<% end %>

app/views/chapter_two_pages/tweets_chart.html.erb
<h2>2.4 Loading, nesting, measuring, and representing data</h2>

<p><strong>Result:</strong></p>
<div id="infovizDiv">
  <svg>
  </svg>
</div>
<%= javascript_tag do %>
  d3.json("<%= asset_path "tweets.json" %>", function(error, data) { dataViz(data.tweets) });

  function dataViz(incomingData) {
    var nestedTweets = d3.nest()
                         .key(function (el) { return el.user; })
                         .entries(incomingData);
    nestedTweets.forEach(function (el) {
      el.numTweets = el.values.length;
    })

    var maxTweets = d3.max(nestedTweets, function(el) { return el.numTweets; });

    var yScale = d3.scale.linear().domain([0, maxTweets]).range([0, 100]);

    d3.select("svg").attr("style", "height: 480px; width: 600px;");
    d3.select("svg")
      .selectAll("rect")
      .data(nestedTweets)
      .enter()
      .append("rect")
      .attr("width", 50)
      .attr("height", function(d) { return yScale(d.numTweets); })
      .attr("x", function(d, i) { return i * 60; })
      .attr("y", function(d) { return 100 - yScale(d.numTweets); })
      .style("fill", "blue")
      .style("stroke", "red")
      .style("stroke-width", "1px").style("opacity", .25);
  }
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D3Samples</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home", root_path %>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>D3.js in Action: Exercises</h1>
<h2>Chapter One</h2>
<ul>
  <li><%= link_to "d3ia", chapter_one_d3ia_path %></li>
  <li><%= link_to "1.6.1 Hello World with divs", chapter_one_hello_world_path %></li>
  <li><%= link_to "1.6.2 Hello World with circles", chapter_one_hello_world_circles_path %></li>
  <li><%= link_to "1.6.3 A conversation with D3", chapter_one_d3_conversation_path %></li>
</ul>
<h2>Chapter Two</h2>
<ul>
  <li><%= link_to "2.2.1 Selections and binding", chapter_two_selections_and_binding_path %></li>
  <li><%= link_to "2.2.2 Accessing Data with inline functions", chapter_two_accessing_data_path %></li>
  <li><%= link_to "2.2.3 Itegrating scales", chapter_two_integrating_scales_path %></li>
  <li><%= link_to "2.3 Loading data, casting it, measuring it, and displaying it as a bar chart",
          chapter_two_bar_chart_path %></li>
  <li><%= link_to "2.4 Loading, nesting, measuring, and representing data",
          chapter_two_tweets_chart_path %></li>
  <li><%= link_to "2.5 Creating a scatterplot", chapter_two_scatterplot_path %></li>
  <li><%= link_to "2.6 Creating labels on <g> elements", chapter_two_g_element_labels_path %></li>
  <li><%= link_to "2.7 Setting the key value in data-binding", chapter_two_key_value_path %></li>
</ul>
<h2>Chapter Three</h2>
<ul>
  <li><%= link_to "3.1.5 External Libraries", chapter_three_external_libraries_path, data: { no_turbolink: true } %></li>
  <li><%= link_to "3.2.1 Events", chapter_three_events_path, data: { no_turbolink: true } %></li>
  <li><%= link_to "3.2.2 Graphical Transitions", chapter_three_graphical_transitions_path, data: { no_turbolink: true } %></li>
  <li><%= link_to "3.2.3 DOM Manipulation", chapter_three_dom_manipulation_path, data: { no_turbolink: true } %></li>
</ul>